local CAE = CrutchAlertsExtensions


---------------------------------------------------------------------
-- Presets that can be added with a button
---------------------------------------------------------------------
CAE.PresetShapes = {
---------------------------------------------------------------------
-- Sets
    ["Roar of Alkosh"] = {
        type = CAE.RECTANGLE,
        rgb = false,
        color = {0, 0.8, 1, 0.1},
        fillColor = {1, 1, 1, 0},
        radius = 9,
        height = 15,
        yOffset = 5,
        forwardOffset = 750,
        conditionalSetId = {232},
        activeBarOnly = true,
        useCameraHeading = false,
    },
    ["Perfected Void Bash (vVH)"] = {
        type = CAE.CIRCLE,
        rgb = true,
        color = {1, 1, 1, 0.5},
        radius = 12,
        yOffset = 5,
        forwardOffset = 0,
        conditionalSetId = {564},
        depthBuffers = false,
    },
    ["Turning Tide"] = {
        type = CAE.RECTANGLE,
        rgb = false,
        color = {0, 0.5, 1, 0.3},
        fillColor = {1, 1, 1, 0},
        radius = 10,
        height = 10,
        yOffset = 5,
        forwardOffset = 500,
        conditionalSetId = {622},
        activeBarOnly = true,
        useCameraHeading = true,
    },

---------------------------------------------------------------------
-- Slotted skills
    ["Ferocious Roar"] = {
        type = CAE.CIRCLE,
        rgb = false,
        color = {1, 1, 1, 0.1},
        radius = 10,
        yOffset = 5,
        forwardOffset = 0,
        conditionalAbilityId = {39113},
        depthBuffers = false,
    },
    ["Bloodclaws"] = {
        type = CAE.CONE,
        rgb = false,
        color = {1, 0.5, 0, 0.3},
        radius = 7,
        height = 20,
        pitch = math.pi / 180 * 120,
        yOffset = 5,
        forwardOffset = 0,
        conditionalAbilityId = {58855, 58879},
        activeBarOnly = true,
        depthBuffers = false,
        useCameraHeading = true,
    },
    ["Claw Fury"] = {
        type = CAE.CONE,
        rgb = false,
        color = {1, 0.5, 0, 0.3},
        radius = 7,
        height = 20,
        pitch = math.pi / 180 * 85,
        yOffset = 5,
        forwardOffset = 0,
        conditionalAbilityId = {58864},
        activeBarOnly = true,
        depthBuffers = false,
        useCameraHeading = true,
    },
    ["Twisting Path"] = {
        type = CAE.CONE,
        rgb = false,
        color = {0.5, 0, 0, 0.3},
        radius = 15,
        height = 15,
        pitch = math.pi / 180 * 65,
        yOffset = 5,
        forwardOffset = 0,
        conditionalAbilityId = {36049},
        activeBarOnly = true,
        depthBuffers = false,
        useCameraHeading = true,
    },
    ["Cleave"] = {
        type = CAE.CONE,
        rgb = false,
        color = {1, 0.7, 0.4, 0.2},
        radius = 6,
        height = 8,
        pitch = math.pi / 180 * 300,
        yOffset = 5,
        forwardOffset = 0,
        conditionalAbilityId = {20919, 38745, 38754},
        activeBarOnly = true,
        depthBuffers = false,
        useCameraHeading = true,
    },
    ["Fatecarver (Simple)"] = {
        type = CAE.RECTANGLE,
        rgb = false,
        color = {0, 1, 0, 0.2},
        fillColor = {1, 1, 1, 0},
        radius = 3,
        height = 23.5,
        yOffset = 5,
        forwardOffset = 1025,
        conditionalAbilityId = {193331, 193397, 193398},
        activeBarOnly = true,
        useCameraHeading = true,
    },
    ["Fatecarver (Clutter)"] = {
        {
            type = CAE.RECTANGLE,
            rgb = false,
            color = {0, 1, 0, 0.2},
            fillColor = {1, 1, 1, 0},
            radius = 3,
            height = 22,
            yOffset = 5,
            forwardOffset = 1100,
            conditionalAbilityId = {193331, 193397, 193398},
            activeBarOnly = true,
            useCameraHeading = true,
        },
        {
            type = CAE.CIRCLE,
            rgb = false,
            color = {0, 1, 0, 0.2},
            radius = 1.5,
            yOffset = 5,
            forwardOffset = 0,
            conditionalAbilityId = {193331, 193397, 193398},
            activeBarOnly = true,
        },
        {
            type = CAE.CIRCLE,
            rgb = false,
            color = {0, 1, 0, 0.2},
            radius = 1.5,
            yOffset = 5,
            pitch = math.pi / 2,
            forwardOffset = 2200,
            conditionalAbilityId = {193331, 193397, 193398},
            activeBarOnly = true,
            depthBuffers = true,
            useCameraHeading = true,
        },
    },
    ["Blockade of Fire"] = {
        type = CAE.RECTANGLE,
        rgb = false,
        color = {1, 0, 0, 0.2},
        fillColor = {1, 1, 1, 0},
        radius = 12,
        height = 18,
        yOffset = 5,
        forwardOffset = 900,
        conditionalAbilityId = {39012},
        activeBarOnly = true,
        useCameraHeading = true,
    },
    ["Blockade of Storms"] = {
        type = CAE.RECTANGLE,
        rgb = false,
        color = {0, 1, 1, 0.2},
        fillColor = {1, 1, 1, 0},
        radius = 12,
        height = 18,
        yOffset = 5,
        forwardOffset = 900,
        conditionalAbilityId = {39018},
        activeBarOnly = true,
        useCameraHeading = true,
    },
    ["Blockade of Frost"] = {
        type = CAE.RECTANGLE,
        rgb = false,
        color = {0, 0, 1, 0.2},
        fillColor = {1, 1, 1, 0},
        radius = 12,
        height = 18,
        yOffset = 5,
        forwardOffset = 900,
        conditionalAbilityId = {39028},
        activeBarOnly = true,
        useCameraHeading = true,
    },
    ["Streak (flat ground)"] = {
        {
            type = CAE.CIRCLE,
            rgb = false,
            color = {1, 1, 1, 0.8},
            radius = 0.5,
            yOffset = 5,
            forwardOffset = 1500,
            conditionalAbilityId = {23234, 23236, 23277},
            depthBuffers = false,
            useCameraHeading = true,
        },
        {
            type = CAE.RECTANGLE,
            solid = true,
            rgb = false,
            color = {1, 1, 1, 0.1},
            radius = 0.1,
            height = 8,
            yOffset = 5,
            forwardOffset = 1500,
            conditionalAbilityId = {23234, 23236, 23277},
            depthBuffers = true,
            pitch = math.pi / 2,
            useCameraHeading = true,
        },
    },

---------------------------------------------------------------------
-- Effects
    ["Deep Fissure (2nd)"] = {
        type = CAE.RECTANGLE,
        rgb = false,
        color = {0.3, 1, 0.8, 0.2},
        fillColor = {0, 1, 1, 0.1},
        radius = 7,
        height = 20,
        yOffset = 5,
        forwardOffset = 1000,
        conditionalEffectId = {178028},
        useCameraHeading = false,
    },
}
